name: manual input workflow

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Persson to greet'
        default: 'world'
        required: true
jobs:
  greet:
    runs-on: windows-latest

    steps:

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name}}"

